services:
  - type: web
    name: adaistra-backend
    env: node
    branch: main
    buildCommand: npm install
    startCommand: node server.js
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
    ports:
      - port: 3000
        http: true